baseurl = "https://adbrei.github.io/qfl-research/"
languageCode = "en-us"
title = "Quantum Federated Learning"
theme = "m10c"
paginate = 8
math = true


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Posts"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Topics"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[taxonomies]
   tag = "tags"

[params]
    author = "Anneliese Brei"
    description = "A University Student's Honors Research"
    menu_item_separator = "-"
    avatar = "network.png"
    Copyright = "Copyright © 2021 Anneliese Brei"
    

    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/adbrei"
    [[params.social]]
        icon = "linkedin"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/anneliese-brei-b19907205"